
#include <string>

#include <SFML/Graphics.hpp>

#include "graphics/gsettings.hpp"
#include "settings.hpp"

using namespace std;
using namespace sf;


/* GRAPHICS PARAMETERS - GENERAL */
// Fonts //
Font tiFont;
const string TIFONTPATH = ".\\resources\\fonts\\SourceSans3-Medium.ttf";
int tiFontSize = 30;
Font bdFont;
const string BDFONTPATH = ".\\resources\\fonts\\SourceSans3-Regular.ttf";
int bdFontSize = 20;
Font msgFont;
const string MSGFONTPATH = ".\\resources\\fonts\\SourceSans3-Semibold.ttf";
int msgFontSize = 16;
Font btFont;
const string BTFONTPATH = ".\\resources\\fonts\\SourceSans3-Light.ttf";
int btFontSize = 14;

// Colors //
const Color OVERLAYBGCOLOR = Color(150, 150, 160);
const Color OVERLAYOUTLINECOLOR = Color(50, 50, 60);
const Color OVERLAYTIBGCOLOR = Color(210, 210, 220);
const Color OVERLAYTIOUTLINECOLOR = Color(100, 100, 110);

const Color TEXTCOLOR = Color(60, 60, 80);

const Color MSGINFOCOLOR = Color(60, 60, 80);
const Color MSGSUCCESSCOLOR = Color(20, 140, 60);
const Color MSGERRORCOLOR = Color(140, 20, 60);

const Color BUTTONCOLOR = Color(40, 40, 50);
const Color BUTTONOUTLINECOLOR = Color(80, 80, 120);
const Color BUTTONTEXTCOLOR = Color(220, 220, 240);
const Color BUTTONCOLORPRESSED = Color(60, 60, 160);
const Color BUTTONOUTLINECOLORPRESSED = Color(100, 100, 200);
const Color BUTTONSUBMITCOLOR = Color(40, 150, 70);
const Color BUTTONSUBMITCOLORPRESSED = Color(60, 180, 100);

const Color CHECKERCOLOR = BUTTONCOLOR;
const Color CHECKEROUTLINECOLOR = BUTTONOUTLINECOLOR;
const Color CHECKERCOLORPRESSED = BUTTONCOLORPRESSED;
const Color CHECKEROUTLINECOLORPRESSED = BUTTONOUTLINECOLORPRESSED;
const Color CHECKERCHECKMARKCOLOR = Color(60, 180, 100);

const Color INPUTBOXCOLOR = BUTTONCOLOR;
const Color INPUTBOXOUTLINECOLOR = BUTTONOUTLINECOLOR;
const Color INPUTBOXTEXTCOLOR = BUTTONTEXTCOLOR;
const Color INPUTBOXOUTLINECOLORPRESSED = BUTTONOUTLINECOLORPRESSED;

const Color SCROLLBARBGCOLOR = Color(30, 30, 40);
const Color SCROLLBARBGOUTLINECOLOR = Color(50, 50, 60);
const Color SCROLLBARCOLOR = Color(60, 60, 70);
const Color SCROLLBAROUTLINECOLOR = BUTTONOUTLINECOLOR;
const Color SCROLLBARCOLORPRESSED = BUTTONCOLORPRESSED;
const Color SCROLLBAROUTLINECOLORPRESSED = BUTTONOUTLINECOLORPRESSED;


/* GRAPHICS PARAMETERS - OVERLAYS */
// Overlay Basics //
const float BOXTRAINS = 250.f;
const float BOXTESTS = 400.f;
const float MARGINS = 10.f;
const float TIBASICW = 46.f;
const float TIMARGINADJUST = (MARGINS*2.f); // 20

const float OVERLAYOUTLINETHICKNESS = 3.f;
const float OVERLAYTIOUTLINETHICKNESS = 3.f;
const float OVERLAYTIROTATION = -90.f;

// Overlays Train //
const float OVERLAYTRAINW = BOXTRAINS + MARGINS; // 260 
const float OVERLAYTRAININITW = OVERLAYTRAINW + TIBASICW + TIMARGINADJUST; // 326
const float OVERLAYTRAINH = (BOXTRAINS*2.f) + (MARGINS*3.f); // 530
const float OVERLAYTRAINPOSX = MARGINS;
const float OVERLAYTRAINPOSY = MARGINS;

const float OVERLAYTRAINTIW = TIBASICW; // 46
const float OVERLAYTRAINTIH = OVERLAYTRAINH - (MARGINS*2.f); // 510
const float OVERLAYTRAINTIPOSX = (MARGINS*2.f);
const float OVERLAYTRAINTIPOSY = (MARGINS*2.f);

// Overlays TEST AND TOOLS //
const float OVERLAYTESTINPUTW = BOXTESTS + TIBASICW + (MARGINS*3.f); // 476
const float OVERLAYTESTINPUTH = BOXTESTS + (MARGINS*2.f); // 420
const float OVERLAYTESTINPUTPOSX = MARGINS;
const float OVERLAYTESTINPUTPOSY = (MARGINS*2.f) + OVERLAYTRAINH;

const float OVERLAYTESTINPUTTIW = TIBASICW; // 46
const float OVERLAYTESTINPUTTIH = OVERLAYTESTINPUTH - (MARGINS*2.f); // 400
const float OVERLAYTESTINPUTTIPOSX = (MARGINS*2.f);
const float OVERLAYTESTINPUTTIPOSY = OVERLAYTESTINPUTPOSY + MARGINS;

const float OVERLAYTOOLSW = BOXTESTS; // 400
const float OVERLAYTOOLSH = BOXTESTS + (MARGINS*2.f); // 420
const float OVERLAYTOOLSPOSX = OVERLAYTESTINPUTPOSX + MARGINS + OVERLAYTESTINPUTW;
const float OVERLAYTOOLSPOSY = (MARGINS*2.f) + OVERLAYTRAINH;

const float OVERLAYTOOLSTIW = OVERLAYTOOLSW - (MARGINS*2.f);
const float OVERLAYTOOLSTIH = TIBASICW;
const float OVERLAYTOOLSTIPOSX = OVERLAYTOOLSPOSX + MARGINS;
const float OVERLAYTOOLSTIPOSY = OVERLAYTOOLSPOSY + MARGINS;

const float OVERLAYTESTOUTPUTW = (BOXTESTS*2.f) + TIBASICW + (MARGINS*4.f); // 886
const float OVERLAYTESTOUTPUTH = BOXTESTS + (MARGINS*2.f); // 420
const float OVERLAYTESTOUTPUTPOSX = OVERLAYTOOLSPOSX + MARGINS + OVERLAYTOOLSW;
const float OVERLAYTESTOUTPUTPOSY = (MARGINS*2.f) + OVERLAYTRAINH;

const float OVERLAYTESTOUTPUTTIW = TIBASICW; // 46
const float OVERLAYTESTOUTPUTTIH = OVERLAYTESTOUTPUTH - (MARGINS*2.f); // 400
const float OVERLAYTESTOUTPUTTIPOSX = OVERLAYTESTOUTPUTPOSX + (MARGINS*2.f) + BOXTESTS;
const float OVERLAYTESTOUTPUTTIPOSY = OVERLAYTESTOUTPUTPOSY + MARGINS;


/* GRAPHICS PARAMETERS - GRID BOXES */
// Grid BoxeS //
const float GRIDTRAININPUTINITPOSX = (MARGINS*3.f) + TIBASICW;
const float GRIDTRAININPUTINITPOSY = (MARGINS*2.f);
const float GRIDTRAININPUTADDOFFSETX = MARGINS + BOXTRAINS;
const float GRIDTRAININPUTADDOFFSETY = 0.f;

const float GRIDTRAINOUTPUTINITPOSX = (MARGINS*3.f) + TIBASICW;
const float GRIDTRAINOUTPUTINITPOSY = (MARGINS*3.f) + BOXTRAINS;
const float GRIDTRAINOUTPUTADDOFFSETX = MARGINS + BOXTRAINS;
const float GRIDTRAINOUTPUTADDOFFSETY = 0.f;

const float GRIDTESTINPUTINITPOSX = (MARGINS*3.f) + TIBASICW;
const float GRIDTESTINPUTINITPOSY = OVERLAYTESTINPUTPOSY + MARGINS;

const float GRIDTESTOUTPUTINITPOSX = OVERLAYTESTOUTPUTPOSX + (MARGINS*3.f) + TIBASICW + BOXTESTS;
const float GRIDTESTOUTPUTINITPOSY = OVERLAYTESTINPUTPOSY + MARGINS;

const float GRIDTESTEDITINITPOSX = OVERLAYTESTOUTPUTPOSX + MARGINS;
const float GRIDTESTEDITINITPOSY = OVERLAYTESTINPUTPOSY + MARGINS;


/* GRAPHICS PARAMETERS - TEXTS */
// Texts Titles //
const string MSGTRAINTI = "Examples Grids";
const float MSGTRAINTIPOSX = 24.f;
const float MSGTRAINTIPOSY = 350.f;

const string MSGTESTINPUTTI = "Test Input Grid ";
const float MSGTESTINPUTTIPOSX = 24.f;
const float MSGTESTINPUTTIPOSY = 890.f;

const string MSGTOOLSTI = "Tools";
const float MSGTOOLSTIPOSX = 658.f;
const float MSGTOOLSTIPOSY = 574.f;

const string MSGTESTOUTPUTTI = "Test Output Grid";
const float MSGTESTOUTPUTTIPOSX = 1329.f;
const float MSGTESTOUTPUTTIPOSY = 880.f;

// Texts Body //
const string MSGLOADTASK = "Load task:";
const float MSGLOADTASKPOSX = 512.f;
const float MSGLOADTASKPOSY = 630.f;

const string MSGTASKNAME = "Task name:";
const float MSGTASKNAMEPOSX = 512.f;
const float MSGTASKNAMEPOSY = 665.f;

const string MSGTASKOUTPUTPAIR = "Task output pair:";
const float MSGTASKOUTPUTPAIRPOSX = 512.f;
const float MSGTASKOUTPUTPAIRPOSY = 700.f;

const string MSGSHOWCELLNUMBER = "Show cell number:";
const float MSGSHOWCELLNUMBERPOSX = 512.f;
const float MSGSHOWCELLNUMBERPOSY = 735.f;

const string MSGCHANGEGRIDSIZE = "Change grid size:";
const float MSGCHANGEGRIDSIZEPOSX = 512.f;
const float MSGCHANGEGRIDSIZEPOSY = 770.f;

const string MSGOTHERCOMMANDS = "Other commands:";
const float MSGOTHERCOMMANDSPOSX = 512.f;
const float MSGOTHERCOMMANDSPOSY = 805.f;

const string MSGCELLPICKER = "Cell Picker:";
const float MSGCELLPICKERPOSX = 512.f;
const float MSGCELLPICKERPOSY = 840.f;


/* GRAPHICS PARAMETERS - MESSAGES */
// Messages Basics //
const float MSGDURATION = 6.f;

const string MSGBASIC = "";

// Messages //
const float MSGPOSY = 940.f;


/* GRAPHICS PARAMETERS - BUTTONS */
// Buttons Basics //
const float CLICKBUTTONDURATION = .1f;

const float BUTTONH = 22.f;
const float BUTTONOUTLINETHICKNESS = 2.f;
const float BUTTONOUTLINETHICKNESSPRESSED = 3.f;

const float BUTTONOFFSETY = 2.f;
const float BUTTONSPACING = 18.f;

// Buttons //
const string BUTTONRANDOMMSG = "Random";
const float BUTTONRANDOMW = 66.f; 
const float BUTTONRANDOMH = BUTTONH;
const float BUTTONRANDOMPOSX = MSGLOADTASKPOSX + 104.f;
const float BUTTONRANDOMPOSY = MSGLOADTASKPOSY + BUTTONOFFSETY;

const string BUTTONOPENMSG = "Browse";
const float BUTTONOPENW = 66.f; 
const float BUTTONOPENH = BUTTONH;
const float BUTTONOPENPOSX = MSGLOADTASKPOSX + 104.f + BUTTONRANDOMW + BUTTONSPACING;
const float BUTTONOPENPOSY = MSGLOADTASKPOSY + BUTTONOFFSETY;

const string BUTTONNEXTTASKMSG = "Next task";
const float BUTTONNEXTTASKW = 70.f; 
const float BUTTONNEXTTASKH = BUTTONH;
const float BUTTONNEXTTASKPOSX = MSGLOADTASKPOSX + 104.f + BUTTONRANDOMW + BUTTONOPENW + (BUTTONSPACING*2);
const float BUTTONNEXTTASKPOSY = MSGLOADTASKPOSY + BUTTONOFFSETY;

const string BUTTONBACKTESTPAIRMSG = "Back";
const float BUTTONBACKTESTPAIRW = 44.f; 
const float BUTTONBACKTESTPAIRH = BUTTONH;
const float BUTTONBACKTESTPAIRPOSX = MSGTASKOUTPUTPAIRPOSX + 200.f;
const float BUTTONBACKTESTPAIRPOSY = MSGTASKOUTPUTPAIRPOSY + BUTTONOFFSETY;

const string BUTTONNEXTTESTPAIRMSG = "Next";
const float BUTTONNEXTTESTPAIRW = 44.f; 
const float BUTTONNEXTTESTPAIRH = BUTTONH;
const float BUTTONNEXTTESTPAIRPOSX = MSGTASKOUTPUTPAIRPOSX + 200.f + BUTTONBACKTESTPAIRW + BUTTONSPACING;
const float BUTTONNEXTTESTPAIRPOSY = MSGTASKOUTPUTPAIRPOSY + BUTTONOFFSETY;

const string BUTTONRESIZEEDITGRIDMSG = "Resize";
const float BUTTONRESIZEEDITGRIDW = 54.f; 
const float BUTTONRESIZEEDITGRIDH = BUTTONH;
const float BUTTONRESIZEEDITGRIDPOSX = MSGCHANGEGRIDSIZEPOSX + 160.f + INPUTBOXW + BUTTONSPACING;
const float BUTTONRESIZEEDITGRIDPOSY = MSGCHANGEGRIDSIZEPOSY + BUTTONOFFSETY;

const string BUTTONRESETEDITGRIDMSG = "Reset";
const float BUTTONRESETEDITGRIDW = 54.f; 
const float BUTTONRESETEDITGRIDH = BUTTONH;
const float BUTTONRESETEDITGRIDPOSX = MSGCHANGEGRIDSIZEPOSX + 160.f + INPUTBOXW + BUTTONRESIZEEDITGRIDW + (BUTTONSPACING*2);
const float BUTTONRESETEDITGRIDPOSY = MSGCHANGEGRIDSIZEPOSY + BUTTONOFFSETY;

const string BUTTONCOPYINPUTMSG = "Copy input";
const float BUTTONCOPYINPUTW = 86.f; 
const float BUTTONCOPYINPUTH = BUTTONH;
const float BUTTONCOPYINPUTPOSX = MSGOTHERCOMMANDSPOSX + 168.f;
const float BUTTONCOPYINPUTPOSY = MSGOTHERCOMMANDSPOSY + BUTTONOFFSETY;

const string BUTTONCOPYOUTPUTMSG = "Copy output";
const float BUTTONCOPYOUTPUTW = 86.f; 
const float BUTTONCOPYOUTPUTH = BUTTONH;
const float BUTTONCOPYOUTPUTPOSX = MSGOTHERCOMMANDSPOSX + 168.f + BUTTONCOPYINPUTW + BUTTONSPACING;
const float BUTTONCOPYOUTPUTPOSY = MSGOTHERCOMMANDSPOSY + BUTTONOFFSETY; 

const string BUTTONCOPYSELMSG = "Copy";
const float BUTTONCOPYSELW = 50.f; 
const float BUTTONCOPYSELH = BUTTONH;
const float BUTTONCOPYSELPOSX = MSGCELLPICKERPOSX + 110.f + CHECKERPICKERS + BUTTONSPACING;
const float BUTTONCOPYSELPOSY = MSGCELLPICKERPOSY + BUTTONOFFSETY; 

const string BUTTONPASTESELMSG = "Paste";
const float BUTTONPASTESELW = 50.f; 
const float BUTTONPASTESELH = BUTTONH;
const float BUTTONPASTESELPOSX = MSGCELLPICKERPOSX + 110.f + CHECKERPICKERS + BUTTONPASTESELW + (BUTTONSPACING*2);
const float BUTTONPASTESELPOSY = MSGCELLPICKERPOSY + BUTTONOFFSETY; 

const string BUTTONFLOODFILLMSG = "Flood fill";
const float BUTTONFLOODFILLW = 70.f; 
const float BUTTONFLOODFILLH = BUTTONH;
const float BUTTONFLOODFILLPOSX = MSGCELLPICKERPOSX + 110.f + CHECKERPICKERS + BUTTONPASTESELW + BUTTONPASTESELW + (BUTTONSPACING*3);
const float BUTTONFLOODFILLPOSY = MSGCELLPICKERPOSY + BUTTONOFFSETY; 

const string BUTTONSUBMITMSG = "Submit!";
const float BUTTONSUBMITW = 58.f; 
const float BUTTONSUBMITH = BUTTONH;
const float BUTTONSUBMITPOSX = OVERLAYTOOLSTIPOSX + (OVERLAYTOOLSTIW/2) + 70.f;
const float BUTTONSUBMITPOSY = OVERLAYTOOLSTIPOSY + 14.f;


/* GRAPHICS PARAMETERS - CHECKERS */
// Checkers //
const float CHECKEROUTLINETHICKNESS = BUTTONOUTLINETHICKNESS;
const float CHECKEROUTLINETHICKNESSPRESSED = BUTTONOUTLINETHICKNESSPRESSED;

const float CHECKERH = 18.f;
const float CHECKEROFFSETY = 4.f;

const float CHECKERCELLNS = CHECKERH;
const float CHECKERCELLNPOSX = MSGSHOWCELLNUMBERPOSX + 174.f;
const float CHECKERCELLNPOSY = MSGSHOWCELLNUMBERPOSY + CHECKEROFFSETY;

const float CHECKERPICKERS = CHECKERH;
const float CHECKERPICKERPOSX = MSGCELLPICKERPOSX + 110.f;
const float CHECKERPICKERPOSY = MSGCELLPICKERPOSY + CHECKEROFFSETY;


/* GRAPHICS PARAMETERS - INPUTBOX */
// Input Box //
const float CLICKINPUTBOXDURATION = CLICKBUTTONDURATION;
const float INPUTBOXCURSORDURATION = .5f;

const float INPUTBOXMAXLENGTH = 5;

const float INPUTBOXW = 48.f;
const float INPUTBOXH = BUTTONH;
const float INPUTBOXPOSX = MSGCHANGEGRIDSIZEPOSX + 160.f;
const float INPUTBOXPOSY = MSGCHANGEGRIDSIZEPOSY + BUTTONOFFSETY;
const float INPUTBOXOUTLINETHICKNESS = BUTTONOUTLINETHICKNESS;
const float INPUTBOXOUTLINETHICKNESSPRESSED = BUTTONOUTLINETHICKNESSPRESSED;
const string INPUTBOXDISPLAY = "3x3";


/* GRAPHICS PARAMETERS - SCROLL BAR */
// Scroll Bar //
const float CLICKSCROLLBARDURATION = .05f;

const float SCROLLBARH = 15.f;
const float SCROLLBARPOSX = 0.f;
const float SCROLLBARPOSY = WINDOWH - SCROLLBARH;

const float SCROLLBAROUTLINETHICKNESS = 1.f;

const float SCROLLBARBGW = WINDOWW; 

const float SCROLLBARW = 200.f; 


